import { Test, TestingModule } from '@nestjs/testing';
import { EmailProvider } from './email.provider';
import { ConfigService } from '@nestjs/config';
import { I18nService } from '../i18n.service';
import * as nodemailer from 'nodemailer';
import * as fs from 'fs';
import * as path from 'path';

// Mock les modules externes
jest.mock('nodemailer');
jest.mock('fs');
jest.mock('path');

describe('EmailProvider', () => {
  let provider: EmailProvider;
  let mockSendMail: jest.Mock;
  let mockTransporter: any;

  beforeEach(async () => {
    // Mock nodemailer
    mockSendMail = jest.fn().mockResolvedValue({ messageId: 'test-123' });
    mockTransporter = {
      sendMail: mockSendMail,
    };
    (nodemailer.createTransport as jest.Mock).mockReturnValue(mockTransporter);

    // Mock fs pour les templates
    (fs.existsSync as jest.Mock).mockImplementation((filePath: string) => {
      // Autoriser les chemins de test
      return filePath.includes('templates') || filePath.includes('layouts') || filePath.includes('partials');
    });

    (fs.readFileSync as jest.Mock).mockImplementation((filePath: string) => {
      if (filePath.includes('layouts/default.hbs')) {
        return '<!DOCTYPE html><html><head><title>{{subject}}</title></head><body><div class="container">{{{body}}}</div></body></html>';
      }
      if (filePath.includes('emails/welcome.hbs')) {
        return '<h2>{{t.title}}</h2><p>Hello {{user.firstName}}</p>';
      }
      if (filePath.includes('partials/header.hbs')) {
        return '<div class="header">Header</div>';
      }
      if (filePath.includes('partials/footer.hbs')) {
        return '<div class="footer">Footer</div>';
      }
      return '';
    });

    // Mock path
    (path.join as jest.Mock).mockImplementation((...parts) => parts.join('/'));

    const module: TestingModule = await Test.createTestingModule({
      providers: [
        EmailProvider,
        {
          provide: ConfigService,
          useValue: {
            get: jest.fn((key: string) => {
              const config: Record<string, string> = {
                MAIL_HOST: 'localhost',
                MAIL_PORT: '1025',
                MAIL_FROM: 'test@example.com',
                FRONTEND_URL: 'http://localhost:3000',
                APP_NAME: 'Test App',
                SUPPORT_EMAIL: 'support@example.com',
                CONTACT_EMAIL: 'contact@example.com',
              };
              return config[key] || null;
            }),
          },
        },
        {
          provide: I18nService,
          useValue: {
            isSupportedLocale: jest.fn(() => true),
            getTranslations: jest.fn((key: string, locale: string) => {
              if (key === 'email.welcome') {
                return {
                  title: 'Welcome to Test App!',
                  greeting: 'Hello',
                  thankYou: 'Thank you for joining!',
                  accountCreated: 'Your account has been created successfully.',
                  getStarted: 'Get Started',
                  support: 'Contact our support team if you need help.',
                  signature: 'Best regards,<br>The Test App Team',
                };
              }
              if (key === 'email.common') {
                return {
                  helpCenter: 'Help Center',
                  contact: 'Contact',
                  privacy: 'Privacy Policy',
                  terms: 'Terms of Service',
                  allRightsReserved: 'All rights reserved',
                  autoGenerated: 'This email was sent automatically. Please do not reply.',
                };
              }
              return {};
            }),
          },
        },
      ],
    }).compile();

    provider = module.get<EmailProvider>(EmailProvider);
  });

  afterEach(() => {
    jest.clearAllMocks();
  });

  it('should be defined', () => {
    expect(provider).toBeDefined();
  });

  describe('sendEmail', () => {
    it('should send email with template and context', async () => {
      const emailOptions = {
        to: 'test@example.com',
        subject: 'Welcome!',
        template: 'welcome',
        context: { 
          user: { firstName: 'John', lastName: 'Doe', email: 'john@example.com' },
        },
        locale: 'en' as const, // ✅ Correction du type
      };

      await provider.sendEmail(emailOptions);

      // ✅ Correction : vérifier le HTML en deux étapes pour éviter les doublons
      expect(mockSendMail).toHaveBeenCalledWith(
        expect.objectContaining({
          to: 'test@example.com',
          subject: 'Welcome!',
          from: 'test@example.com',
        })
      );
      
      // Vérifier que le HTML contient les deux textes attendus
      const callArgs = mockSendMail.mock.calls[0][0];
      expect(callArgs.html).toContain('Welcome to Test App!');
      expect(callArgs.html).toContain('Hello John');
    });

    it('should send email with HTML content', async () => {
      const emailOptions = {
        to: 'test@example.com',
        subject: 'Test Subject',
        html: '<p>Test HTML content</p>',
      };

      await provider.sendEmail(emailOptions);

      expect(mockSendMail).toHaveBeenCalledWith(
        expect.objectContaining({
          to: 'test@example.com',
          subject: 'Test Subject',
          html: '<p>Test HTML content</p>',
          from: 'test@example.com',
        })
      );
    });

    it('should send email with text content', async () => {
      const emailOptions = {
        to: 'test@example.com',
        subject: 'Test Subject',
        text: 'Test text content',
      };

      await provider.sendEmail(emailOptions);

      expect(mockSendMail).toHaveBeenCalledWith(
        expect.objectContaining({
          to: 'test@example.com',
          subject: 'Test Subject',
          text: 'Test text content',
          from: 'test@example.com',
        })
      );
    });

    it('should handle multiple recipients', async () => {
      const emailOptions = {
        to: ['user1@example.com', 'user2@example.com'],
        subject: 'Test Subject',
        text: 'Hello both!',
      };

      await provider.sendEmail(emailOptions);

      expect(mockSendMail).toHaveBeenCalledWith(
        expect.objectContaining({
          to: 'user1@example.com, user2@example.com',
          subject: 'Test Subject',
          text: 'Hello both!',
          from: 'test@example.com',
        })
      );
    });

    it('should handle attachments', async () => {
      const emailOptions = {
        to: 'test@example.com',
        subject: 'With Attachment',
        text: 'Please see attached file',
        attachments: [
          { filename: 'document.pdf', path: '/tmp/document.pdf' },
        ],
      };

      await provider.sendEmail(emailOptions);

      expect(mockSendMail).toHaveBeenCalledWith(
        expect.objectContaining({
          to: 'test@example.com',
          subject: 'With Attachment',
          text: 'Please see attached file',
          from: 'test@example.com',
          attachments: expect.arrayContaining([
            expect.objectContaining({
              filename: 'document.pdf',
              path: '/tmp/document.pdf',
            }),
          ]),
        })
      );
    });

    it('should use default locale when not provided', async () => {
      const emailOptions = {
        to: 'test@example.com',
        subject: 'Test',
        template: 'welcome',
        context: { user: { firstName: 'John' } },
        // locale non fourni → devrait utiliser 'fr' par défaut
      } as any;

      await provider.sendEmail(emailOptions);

      expect(mockSendMail).toHaveBeenCalled();
    });
  });

  describe('compileEmail', () => {
    it('should compile email with layout and template', async () => {
      const context = {
        subject: 'Test Email',
        user: { firstName: 'Alice' },
        locale: 'en' as const,
        platform: { name: 'Test App' },
        year: 2026,
        currentDate: 'Thursday, July 13, 2026',
        t: {
          title: 'Welcome!',
          greeting: 'Hello',
        },
        common: {
          helpCenter: 'Help Center',
        },
      };

      const result = await (provider as any).compileEmail('welcome', context);
      
      expect(result).toContain('<!DOCTYPE html>');
      expect(result).toContain('Welcome!');
      expect(result).toContain('Hello Alice');
      expect(result).toContain('<div class="container">');
    });
  });

  describe('prepareFullContext', () => {
    it('should prepare full context with platform data and translations', async () => {
      const result = await (provider as any).prepareFullContext(
        'welcome',
        'Welcome!',
        { user: { firstName: 'Bob' } },
        'en' as const,
      );

      expect(result.subject).toBe('Welcome!');
      expect(result.user.firstName).toBe('Bob');
      expect(result.platform.name).toBe('Test App');
      expect(result.t.title).toBeDefined();
      expect(result.common.helpCenter).toBeDefined();
      expect(result.year).toBe(2026);
    });
  });
});