import { Test, TestingModule } from '@nestjs/testing';
import { AuthService } from './auth.service';
import { UsersService } from '../users/users.service';
import { JwtService } from '@nestjs/jwt';
import { NotificationService } from '../notifications/notification.service';
import { I18nService } from '../notifications/i18n.service';
import { UserRole } from 'src/users/user.schema';

// Mock services
const mockUsersService = {
  create: jest.fn(),
  findByEmail: jest.fn(),
  validateUser: jest.fn(),
  findOne: jest.fn(),
  update: jest.fn(),
};

const mockJwtService = {
  sign: jest.fn(),
  signAsync: jest.fn(),
  verify: jest.fn(),
};

const mockNotificationService = {
  sendEmail: jest.fn(),
  sendSms: jest.fn(),
  scheduleEmail: jest.fn(),
  scheduleSms: jest.fn(),
};

const mockI18nService = {
  getTranslations: jest.fn().mockImplementation((key) => {
    // Retourner des traductions de test selon la clé
    if (key === 'email.welcome') {
      return {
        subject: 'Welcome to Matsak!',
        title: 'Welcome to Matsak!',
        greeting: 'Hello',
        thankYou: 'Thank you for joining!',
        accountCreated: 'Your account has been created successfully.',
        getStarted: 'Get Started',
        support: 'Contact our support team if you need help.',
        signature: 'Best regards,<br>The Matsak Team',
        createdAt: 'Your account was created on',
        date: 'Date:',
      };
    }
    if (key === 'email.common') {
      return {
        helpCenter: 'Help Center',
        contact: 'Contact',
        privacy: 'Privacy Policy',
        terms: 'Terms of Service',
        allRightsReserved: 'All rights reserved',
        autoGenerated:
          'This email was sent automatically. Please do not reply.',
      };
    }
    return {};
  }),
  isSupportedLocale: jest.fn().mockReturnValue(true),
};

describe('AuthService', () => {
  let service: AuthService;
  let usersService: UsersService;
  let jwtService: JwtService;
  let notificationService: NotificationService;
  let i18nService: I18nService;

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [
        AuthService,
        {
          provide: UsersService,
          useValue: mockUsersService,
        },
        {
          provide: JwtService,
          useValue: mockJwtService,
        },
        {
          provide: NotificationService,
          useValue: mockNotificationService,
        },
        {
          provide: I18nService,
          useValue: mockI18nService,
        },
      ],
    }).compile();

    service = module.get<AuthService>(AuthService);
    usersService = module.get<UsersService>(UsersService);
    jwtService = module.get<JwtService>(JwtService);
    notificationService = module.get<NotificationService>(NotificationService);
    i18nService = module.get<I18nService>(I18nService);

    // ✅ MOCK DE LA MÉTHODE PRIVÉE POUR ÉVITER LES FUITES DE TIMERS
    (service as any).retryWelcomeEmailLater = jest
      .fn()
      .mockResolvedValue(undefined);
  });

  afterEach(() => {
    jest.clearAllMocks();
  });

  it('should be defined', () => {
    expect(service).toBeDefined();
    expect(usersService).toBeDefined();
    expect(jwtService).toBeDefined();
    expect(notificationService).toBeDefined();
    expect(i18nService).toBeDefined();
  });

  describe('register', () => {
    it('should register a new user successfully', async () => {
      // Données d'entrée
      const createUserDto = {
        name: 'Doe',
        firstname: 'John',
        email: 'john.doe@example.com',
        password: 'Password123',
        role: UserRole.USER,
        locale: 'en' as const,
      };

      const mockUser = {
        _id: 'user123',
        name: 'Doe',
        firstname: 'John',
        email: 'john.doe@example.com',
        role: 'user',
        locale: 'en',
        createdAt: new Date(),
        _idToString: () => 'user123',
      };

      const mockFullUser = {
        ...mockUser,
        current_team: null,
      };

      mockUsersService.findByEmail.mockResolvedValue(null);
      mockUsersService.create.mockResolvedValue(mockUser);
      mockUsersService.findOne.mockResolvedValue(mockFullUser);
      mockJwtService.signAsync.mockResolvedValue('fake-jwt-token');
      mockNotificationService.sendEmail.mockResolvedValue(undefined);

      const result = await service.register(createUserDto);

      expect(usersService.findByEmail).toHaveBeenCalledWith(
        createUserDto.email,
      );
      expect(usersService.create).toHaveBeenCalledWith(createUserDto);
      expect(usersService.findOne).toHaveBeenCalledWith({ _id: 'user123' });
      expect(jwtService.signAsync).toHaveBeenCalled();
      expect(notificationService.sendEmail).toHaveBeenCalled();

      expect(result).toEqual({
        accessToken: 'fake-jwt-token',
        user: 'user123',
        role: 'user',
        current_team: null,
        message: 'User registered successfully',
      });
    });

    it('should throw conflict exception if user already exists', async () => {
      const createUserDto = {
        name: 'Doe',
        firstname: 'John',
        email: 'john.doe@example.com',
        password: 'password123',
        role: UserRole.USER,
        locale: 'en' as const,
      };

      const existingUser = {
        _id: 'existing123',
        email: 'john.doe@example.com',
        locale: 'en',
      };

      mockUsersService.findByEmail.mockResolvedValue(existingUser);

      await expect(service.register(createUserDto)).rejects.toThrow();

      expect(usersService.findByEmail).toHaveBeenCalledWith(
        createUserDto.email,
      );
      expect(usersService.create).not.toHaveBeenCalled();
      expect(notificationService.sendEmail).not.toHaveBeenCalled();
    });

    it('should handle email sending failure gracefully', async () => {
      const createUserDto = {
        name: 'Doe',
        firstname: 'John',
        email: 'john.doe@example.com',
        password: 'password123',
        role: UserRole.USER,
        locale: 'en' as const,
      };

      const mockUser = {
        _id: 'user123',
        name: 'Doe',
        firstname: 'John',
        email: 'john.doe@example.com',
        role: 'user',
        locale: 'en',
        createdAt: new Date(),
        _idToString: () => 'user123',
      };

      mockUsersService.findByEmail.mockResolvedValue(null);
      mockUsersService.create.mockResolvedValue(mockUser);
      mockUsersService.findOne.mockResolvedValue({
        ...mockUser,
        current_team: null,
      });
      mockJwtService.signAsync.mockResolvedValue('fake-jwt-token');

      mockNotificationService.sendEmail.mockRejectedValue(
        new Error('Email failed'),
      );

      const result = await service.register(createUserDto);

      expect(result).toEqual({
        accessToken: 'fake-jwt-token',
        user: 'user123',
        role: 'user',
        current_team: null,
        message: 'User registered successfully',
        warnings: expect.arrayContaining([
          expect.stringContaining(
            "L'email de bienvenue n'a pas pu être envoyé",
          ),
        ]),
      });

      expect(notificationService.sendEmail).toHaveBeenCalled();
    });
  });

  describe('login', () => {
    it('should login user successfully', async () => {
      const loginDto = {
        email: 'john.doe@example.com',
        password: 'password123',
      };

      const mockUser = {
        _id: 'user123',
        email: 'john.doe@example.com',
        role: 'user',
        locale: 'en',
      };

      const mockFullUser = {
        ...mockUser,
        current_team: null,
      };

      mockUsersService.validateUser.mockResolvedValue(mockUser);
      mockUsersService.findOne.mockResolvedValue(mockFullUser);
      mockJwtService.signAsync.mockResolvedValue('fake-jwt-token');

      const result = await service.login({ loginDto });

      expect(usersService.validateUser).toHaveBeenCalledWith(
        loginDto.email,
        loginDto.password,
      );
      expect(usersService.findOne).toHaveBeenCalledWith({ _id: 'user123' });
      expect(jwtService.signAsync).toHaveBeenCalled();

      expect(result).toEqual({
        accessToken: 'fake-jwt-token',
        user: 'user123',
        role: 'user',
        locale: 'en',
        current_team: null,
      });
    });

    it('should throw unauthorized for invalid credentials', async () => {
      const loginDto = {
        email: 'wrong@example.com',
        password: 'wrongpassword',
      };

      mockUsersService.validateUser.mockResolvedValue(null);

      await expect(service.login({ loginDto })).rejects.toThrow();
      expect(usersService.validateUser).toHaveBeenCalledWith(
        loginDto.email,
        loginDto.password,
      );
    });
  });

  describe('resetUserPasswordRequest', () => {
    it('should initiate password reset for existing user', async () => {
      const email = 'john.doe@example.com';
      const existingUser = {
        id: 'user123',
        email: 'john.doe@example.com',
        firstName: 'John',
        isResettingPassword: false,
      };

      mockUsersService.findByEmail.mockResolvedValue(existingUser);
      mockUsersService.update.mockResolvedValue({});

      const result = await service.resetUserPasswordRequest({ email });

      expect(usersService.findByEmail).toHaveBeenCalledWith(email);
      expect(usersService.update).toHaveBeenCalledWith(
        existingUser.id,
        expect.objectContaining({
          isResettingPassword: true,
          resetPasswordToken: expect.any(String),
        }),
      );
      expect(result).toEqual({
        error: false,
        message: 'Please check your email to reset your password.',
      });
    });

    it('should throw error if user not found', async () => {
      const email = 'nonexistent@example.com';

      mockUsersService.findByEmail.mockResolvedValue(null);

      await expect(
        service.resetUserPasswordRequest({ email }),
      ).rejects.toThrow();
      expect(usersService.findByEmail).toHaveBeenCalledWith(email);
    });
  });

  describe('updateUserLocale', () => {
    it('should update user locale successfully', async () => {
      const userId = 'user123';
      const newLocale = 'fr' as const;

      const mockUpdatedUser = {
        _id: userId,
        email: 'test@example.com',
        locale: newLocale,
      };

      mockUsersService.update.mockResolvedValue(mockUpdatedUser);

      const result = await service.updateUserLocale(userId, newLocale);

      expect(usersService.update).toHaveBeenCalledWith(
        { _id: userId },
        { locale: newLocale },
      );
      expect(result).toEqual(mockUpdatedUser);
    });
  });
});
